import { useState } from 'react';
import type { SavedView, WorkspaceDocument } from '@utm/core';
import { CloseIcon } from '../../components/ui/icons';
import { exampleViewFieldValue, viewFieldGroups, viewFieldLabel, viewFieldOptions } from './fieldCatalog';

export function DisplayedFieldsEditor({ workspace, view, onChange }: { workspace: WorkspaceDocument; view: SavedView; onChange: (view: SavedView) => void }) {
  const [manualField, setManualField] = useState(''); const [draggedField, setDraggedField] = useState<string | null>(null);
  const toggle = (path: string) => onChange({ ...view, fields: view.fields.includes(path) ? view.fields.filter((field) => field !== path) : [...view.fields, path] });
  const move = (index: number, offset: number) => { const target = index + offset; if (target < 0 || target >= view.fields.length) return; const fields = [...view.fields]; [fields[index], fields[target]] = [fields[target]!, fields[index]!]; onChange({ ...view, fields }); };
  const moveTo = (field: string, target: string) => { if (field === target) return; const fields = view.fields.filter((entry) => entry !== field); fields.splice(fields.indexOf(target), 0, field); onChange({ ...view, fields }); };
  return <section className="visual-query-display" aria-label="Display fields"><h3 className="query-builder-heading">2. Show in results</h3><p className="builder-status">Choose the columns or details shown for every matching item. This does not change which items match; their order is the display order.</p>
    <details className="display-fields-example"><summary>Preview with a fully filled example item</summary><p className="display-fields-help">Drag a field to change its order, or hide it with ×.</p><div>{view.fields.length ? view.fields.map((field) => <span key={field} draggable onDragStart={() => setDraggedField(field)} onDragEnd={() => setDraggedField(null)} onDragOver={(event) => event.preventDefault()} onDrop={() => { if (draggedField) moveTo(draggedField, field); setDraggedField(null); }}><button className="preview-field-remove" aria-label={`Hide ${viewFieldLabel(workspace, field)}`} onClick={() => toggle(field)}><CloseIcon /></button><small>{viewFieldLabel(workspace, field)}</small>{exampleViewFieldValue(field)}</span>) : <p>Select fields below to preview them here.</p>}</div></details>
    <div className="builder-actions"><button className="secondary compact-action" onClick={() => onChange({ ...view, fields: viewFieldOptions(workspace).map((field) => field.path) })}>Select all</button><button className="secondary compact-action" onClick={() => onChange({ ...view, fields: [] })}>Hide all</button></div>
    <div className="field-groups">{viewFieldGroups(workspace).map((group) => <details key={group.name}><summary>{group.name}</summary><div className="field-options">{group.fields.map((field) => <label className="check" key={field.path}><input type="checkbox" checked={view.fields.includes(field.path)} onChange={() => toggle(field.path)} />{field.label}<small>{field.path}</small></label>)}</div></details>)}</div>
    <div className="manual-field"><input aria-label="Custom field path" placeholder="Any path, e.g. custom.client" value={manualField} onChange={(event) => setManualField(event.target.value)} /><button className="secondary compact-action" disabled={!manualField.trim() || view.fields.includes(manualField.trim())} onClick={() => { const path = manualField.trim(); onChange({ ...view, fields: [...view.fields, path] }); setManualField(''); }}>+ Add path</button></div>
    {view.fields.length > 0 && <div className="selected-fields"><span className="selected-fields-title">Display order</span>{view.fields.map((field, index) => <div key={field}><code>{field}</code><div><button aria-label={`Move ${field} up`} disabled={index === 0} onClick={() => move(index, -1)}>↑</button><button aria-label={`Move ${field} down`} disabled={index === view.fields.length - 1} onClick={() => move(index, 1)}>↓</button><button aria-label={`Hide ${field}`} onClick={() => toggle(field)}><CloseIcon /></button></div></div>)}</div>}
  </section>;
}
