import { useState } from 'react';
import type { SavedView, WorkspaceDocument } from '@utm/core';
import { CloseIcon } from '../../components/ui/icons';
import { Button, Checkbox, Disclosure, IconButton, Input } from '../../components/ui/primitives';
import { useReorderList } from '../../components/ui/useReorderList';
import { FieldIcon } from '../items';
import { exampleViewFieldValue, viewFieldGroups, viewFieldLabel, viewFieldOptions } from './fieldCatalog';

export function DisplayedFieldsEditor({ workspace, view, onChange }: { workspace: WorkspaceDocument; view: SavedView; onChange: (view: SavedView) => void }) {
  const [manualField, setManualField] = useState(''); const [draggedField, setDraggedField] = useState<string | null>(null);
  const toggle = (path: string) => onChange({ ...view, fields: view.fields.includes(path) ? view.fields.filter((field) => field !== path) : [...view.fields, path] });
  const moveTo = (field: string, target: string) => { if (field === target) return; const fields = view.fields.filter((entry) => entry !== field); fields.splice(fields.indexOf(target), 0, field); onChange({ ...view, fields }); };
  const reorder = useReorderList(view.fields, (fields) => onChange({ ...view, fields }));
  return <section className="visual-query-display" aria-label="Display fields"><p className="builder-status">Choose the columns or details shown for every matching item. This does not change which items match; their order is the display order.</p>
    <Disclosure uiKey="view-editor:display-preview" persist={false} className="display-fields-example" summary="Preview with a fully filled example item"><p className="display-fields-help">Drag a field to change its order, or hide it with ×.</p><div>{view.fields.length ? view.fields.map((field) => { const label = viewFieldLabel(workspace, field); return <span key={field} draggable onDragStart={() => setDraggedField(field)} onDragEnd={() => setDraggedField(null)} onDragOver={(event) => event.preventDefault()} onDrop={() => { if (draggedField) moveTo(draggedField, field); setDraggedField(null); }}><IconButton size="compact" variant="ghost" className="preview-field-remove" aria-label={`Hide ${label}`} onClick={() => toggle(field)}><CloseIcon /></IconButton><small><FieldIcon path={field} label={label} />{label}</small>{exampleViewFieldValue(field)}</span>; }) : <p>Select fields below to preview them here.</p>}</div></Disclosure>
    <div className="builder-actions"><Button size="compact" onClick={() => onChange({ ...view, fields: viewFieldOptions(workspace).map((field) => field.path) })}>Select all</Button><Button size="compact" onClick={() => onChange({ ...view, fields: [] })}>Hide all</Button></div>
    <div className="field-groups">{viewFieldGroups(workspace).map((group) => <Disclosure uiKey={`view-editor:fields:${group.name}`} persist={false} key={group.name} summary={group.name}><div className="field-options">{group.fields.map((field) => <Checkbox key={field.path} checked={view.fields.includes(field.path)} onChange={() => toggle(field.path)} label={<span className="field-option-label"><span><FieldIcon path={field.path} label={field.label} />{field.label}</span><small>{field.path}</small></span>} />)}</div></Disclosure>)}</div>
    <div className="manual-field"><Input aria-label="Custom field path" placeholder="Any path, e.g. custom.client" value={manualField} onChange={(event) => setManualField(event.target.value)} /><Button size="compact" disabled={!manualField.trim() || view.fields.includes(manualField.trim())} onClick={() => { const path = manualField.trim(); onChange({ ...view, fields: [...view.fields, path] }); setManualField(''); }}>+ Add path</Button></div>
    {view.fields.length > 0 && <div className="selected-fields" ref={reorder.container}><span className="selected-fields-title">Display order</span>{view.fields.map((field, index) => { const label = viewFieldLabel(workspace, field); return <div key={field} {...reorder.rowProps(index)}>{reorder.handle(index, label)}<code><FieldIcon path={field} label={label} />{label}</code><IconButton size="compact" variant="ghost" aria-label={`Hide ${field}`} onClick={() => toggle(field)}><CloseIcon /></IconButton></div>; })}</div>}
  </section>;
}
