import { parseSortSource, type ViewSortRule, type WorkspaceDocument } from '@utm/core';
import { CodeEditor } from '../../components/ui/CodeEditor'; import { CloseIcon } from '../../components/ui/icons'; import { Button, Field, IconButton, Input, Select, Surface } from '../../components/ui/primitives'; import { SectionGuide } from '../../components/ui/SectionGuide';
import { viewFieldGroups, viewFieldOptions } from './fieldCatalog'; import { toSqlSort } from './sorting';
import { ViewEditorSection } from './ViewEditorSection';
export function ViewSortingEditor({ workspace, rules, source, onRules, onSource }: { workspace: WorkspaceDocument; rules: ViewSortRule[]; source: string; onRules: (rules: ViewSortRule[]) => void; onSource: (source: string, parsed?: ViewSortRule[]) => void }) {
  const isKnownSort = (expression: string) => ['listOrder', 'areaOrder', 'projectOrder'].includes(expression) || viewFieldOptions(workspace).some((field) => field.path === expression);
  const update = (index: number, patch: Partial<ViewSortRule>) => onRules(rules.map((rule, at) => at === index ? { ...rule, ...patch } : rule));
  const move = (index: number, offset: number) => { const target = index + offset; if (target < 0 || target >= rules.length) return; const next = [...rules]; [next[index], next[target]] = [next[target]!, next[index]!]; onRules(next); };
  return <ViewEditorSection sectionKey="sorting" title="Sorting"><Surface variant="muted" className="query-builder sort-builder"><p className="builder-status">Rules run from top to bottom. Later rules break ties from earlier ones.</p><SectionGuide title="Sorting examples"><p><code>priority desc nulls last</code> puts urgent items first. Add <code>lower(title) asc nulls last</code> on the next line to order items with the same priority alphabetically.</p></SectionGuide>
    <div className="sort-rules">{rules.map((rule, index) => <Surface className="sort-rule" key={`${index}-${rule.expression}`}><Field label="Sort by"><Select aria-label={`Sort field ${index + 1}`} value={isKnownSort(rule.expression) ? rule.expression : '__custom__'} onChange={(event) => { const expression = event.target.value === '__custom__' ? 'lower(title)' : event.target.value; update(index, ['listOrder', 'areaOrder', 'projectOrder'].includes(expression) ? { expression, direction: 'desc' } : { expression }); }}><optgroup label="Organization"><option value="areaOrder">Area order — priority, then manual order</option><option value="projectOrder">Project order — priority, then manual order</option><option value="listOrder">List order — priority, then newest</option></optgroup>{viewFieldGroups(workspace).map((group) => <optgroup label={group.name} key={group.name}>{group.fields.map((field) => <option value={field.path} key={field.path}>{field.label}</option>)}</optgroup>)}<optgroup label="Advanced"><option value="__custom__">Custom expression…</option></optgroup></Select>{!isKnownSort(rule.expression) && <Input className="sort-custom-expression mono" aria-label={`Custom sort expression ${index + 1}`} value={rule.expression} onChange={(event) => update(index, { expression: event.target.value })} placeholder="lower(title)" />}</Field><Field label="Direction"><Select aria-label={`Sort direction ${index + 1}`} value={rule.direction} onChange={(event) => update(index, { direction: event.target.value as ViewSortRule['direction'] })}><option value="asc">Ascending</option><option value="desc">Descending</option></Select></Field><Field label="Empty values"><Select aria-label={`Empty values ${index + 1}`} value={rule.nulls} onChange={(event) => update(index, { nulls: event.target.value as ViewSortRule['nulls'] })}><option value="last">Last</option><option value="first">First</option></Select></Field><div className="rule-order"><IconButton size="compact" aria-label={`Move sort ${index + 1} up`} disabled={index === 0} onClick={() => move(index, -1)}>↑</IconButton><IconButton size="compact" aria-label={`Move sort ${index + 1} down`} disabled={index === rules.length - 1} onClick={() => move(index, 1)}>↓</IconButton><IconButton size="compact" aria-label={`Remove sort ${index + 1}`} onClick={() => onRules(rules.filter((_rule, at) => at !== index))}><CloseIcon /></IconButton></div></Surface>)}</div>
    {rules.some((rule) => ['listOrder', 'areaOrder', 'projectOrder'].includes(rule.expression)) && <p className="builder-status">Descending puts higher priorities first. Area and Project ties use the manual order from Settings; plain list ties use recency.</p>}
    <Button size="compact" onClick={() => onRules([...rules, { expression: 'updatedAt', direction: 'desc', nulls: 'last' }])}>+ Add sort rule</Button><Field className="dsl-field sort-dsl" label="SQL-like sorting" hint={<>One rule per line. SQL preview: {toSqlSort(source)}</>}><CodeEditor language="dsl" ariaLabel="SQL-like sorting" rows={4} value={source} onChange={(value) => { try { onSource(value, parseSortSource(value)); } catch { onSource(value); } }} /></Field>
  </Surface></ViewEditorSection>;
}
