import { parseSortSource, type ViewSortRule, type WorkspaceDocument } from '@utm/core';
import { CodeEditor } from '../../components/ui/CodeEditor'; import { CloseIcon } from '../../components/ui/icons'; import { SectionGuide } from '../../components/ui/SectionGuide';
import { viewFieldGroups, viewFieldOptions } from './fieldCatalog'; import { toSqlSort } from './sorting';
export function ViewSortingEditor({ workspace, rules, source, onRules, onSource }: { workspace: WorkspaceDocument; rules: ViewSortRule[]; source: string; onRules: (rules: ViewSortRule[]) => void; onSource: (source: string, parsed?: ViewSortRule[]) => void }) {
  const update = (index: number, patch: Partial<ViewSortRule>) => onRules(rules.map((rule, at) => at === index ? { ...rule, ...patch } : rule));
  const move = (index: number, offset: number) => { const target = index + offset; if (target < 0 || target >= rules.length) return; const next = [...rules]; [next[index], next[target]] = [next[target]!, next[index]!]; onRules(next); };
  return <details className="view-editor-section"><summary>Sorting</summary><fieldset className="query-builder sort-builder"><p className="builder-status">Rules run from top to bottom. Later rules break ties from earlier ones.</p><SectionGuide title="Sorting examples"><p><code>priority desc nulls last</code> puts urgent items first. Add <code>lower(title) asc nulls last</code> on the next line to order items with the same priority alphabetically.</p></SectionGuide>
    <div className="sort-rules">{rules.map((rule, index) => <div className="sort-rule" key={`${index}-${rule.expression}`}><label>Sort by<select aria-label={`Sort field ${index + 1}`} value={viewFieldOptions(workspace).some((field) => field.path === rule.expression) ? rule.expression : '__custom__'} onChange={(event) => update(index, { expression: event.target.value === '__custom__' ? 'lower(title)' : event.target.value })}>{viewFieldGroups(workspace).map((group) => <optgroup label={group.name} key={group.name}>{group.fields.map((field) => <option value={field.path} key={field.path}>{field.label}</option>)}</optgroup>)}<optgroup label="Advanced"><option value="__custom__">Custom expression…</option></optgroup></select>{!viewFieldOptions(workspace).some((field) => field.path === rule.expression) && <input className="sort-custom-expression mono" aria-label={`Custom sort expression ${index + 1}`} value={rule.expression} onChange={(event) => update(index, { expression: event.target.value })} placeholder="lower(title)" />}</label><label>Direction<select aria-label={`Sort direction ${index + 1}`} value={rule.direction} onChange={(event) => update(index, { direction: event.target.value as ViewSortRule['direction'] })}><option value="asc">Ascending</option><option value="desc">Descending</option></select></label><label>Empty values<select aria-label={`Empty values ${index + 1}`} value={rule.nulls} onChange={(event) => update(index, { nulls: event.target.value as ViewSortRule['nulls'] })}><option value="last">Last</option><option value="first">First</option></select></label><div className="rule-order"><button className="secondary compact-action" aria-label={`Move sort ${index + 1} up`} disabled={index === 0} onClick={() => move(index, -1)}>↑</button><button className="secondary compact-action" aria-label={`Move sort ${index + 1} down`} disabled={index === rules.length - 1} onClick={() => move(index, 1)}>↓</button><button className="secondary compact-action" aria-label={`Remove sort ${index + 1}`} onClick={() => onRules(rules.filter((_rule, at) => at !== index))}><CloseIcon /></button></div></div>)}</div>
    <button className="secondary compact-action" onClick={() => onRules([...rules, { expression: 'updatedAt', direction: 'desc', nulls: 'last' }])}>+ Add sort rule</button><label className="dsl-field sort-dsl">SQL-like sorting<span className="hint">One rule per line. SQL preview: {toSqlSort(source)}</span><CodeEditor language="dsl" ariaLabel="SQL-like sorting" rows={4} value={source} onChange={(value) => { try { onSource(value, parseSortSource(value)); } catch { onSource(value); } }} /></label>
  </fieldset></details>;
}
