import { expect, test } from '@playwright/test';

test('infers missing event boundaries and generates the script on Save without Apply', async ({ page }) => {
  await page.goto('/');
  await page.getByLabel('Workspace name').fill('Automatic program');
  await page.getByLabel('Password', { exact: true }).fill('program-test-password');
  await page.getByLabel('Confirm password').fill('program-test-password');
  await page.getByRole('button', { name: 'Create encrypted workspace' }).click();
  await page.getByPlaceholder('Add new item').fill('New program');
  await page.getByPlaceholder('Add new item').press('Enter');
  const editor = page.getByRole('dialog', { name: 'Item editor', exact: true });
  const program = editor.locator('.event-program');
  await program.locator(':scope > summary').click();
  await program.getByRole('button', { name: 'Add block', exact: true }).click();
  await program.getByLabel('Block title 1', { exact: true }).fill('First');
  await program.getByLabel('Block start 1', { exact: true }).fill('2030-09-21T17:00');
  await program.getByLabel('Block end 1', { exact: true }).fill('2030-09-21T17:45');
  await program.getByRole('button', { name: 'Add block', exact: true }).click();
  await program.getByLabel('Block title 2', { exact: true }).fill('Second');
  await expect(program.getByLabel('Block start 2', { exact: true })).toHaveValue('2030-09-21T17:45');
  await editor.locator('[data-editor-section="dates"] > summary').click();
  await expect(editor.getByLabel('Event opens', { exact: true })).toHaveValue('2030-09-21T17:00');
  await expect(editor.getByLabel('Event ends', { exact: true })).toHaveValue('2030-09-21T18:15');
  await editor.getByRole('button', { name: 'Save item', exact: true }).click();
  await expect(editor).toBeHidden();
  await page.getByText('New program', { exact: true }).first().click();
  await expect(editor.locator('.item-script-row')).toHaveCount(1);
  await program.locator(':scope > summary').click();
  await program.getByLabel('Block title 1', { exact: true }).fill('Discarded edit');
  await editor.getByRole('button', { name: 'Cancel', exact: true }).click();
  await page.getByText('New program', { exact: true }).first().click();
  await program.locator(':scope > summary').click();
  await expect(program.getByLabel('Block title 1', { exact: true })).toHaveValue('First');
});

test('program edits, shifts, trims with confirmation and saves one managed script', async ({ page }) => {
  await page.goto('/');
  await page.getByLabel('Workspace name').fill('Program checks');
  await page.getByLabel('Password', { exact: true }).fill('program-test-password');
  await page.getByLabel('Confirm password').fill('program-test-password');
  await page.getByRole('button', { name: 'Create encrypted workspace' }).click();
  await page.getByPlaceholder('Add new item').fill('Program workshop');
  await page.getByPlaceholder('Add new item').press('Enter');
  const editor = page.getByRole('dialog', { name: 'Item editor', exact: true });
  const dates = editor.locator('[data-editor-section="dates"]');
  await dates.locator(':scope > summary').click();
  await editor.getByLabel('Event opens', { exact: true }).fill('2030-09-21T17:00');
  await editor.getByLabel('Event ends', { exact: true }).fill('2030-09-21T21:00');
  const program = editor.locator('.event-program');
  await program.locator(':scope > summary').click();
  await program.getByRole('button', { name: 'Add block', exact: true }).click();
  await program.getByLabel('Block title 1', { exact: true }).fill('Lesson');
  await program.getByLabel('Block end 1', { exact: true }).fill('2030-09-21T17:45');
  await program.getByRole('button', { name: 'Add block', exact: true }).click();
  await program.getByLabel('Block title 2', { exact: true }).fill('Tea');
  await program.getByLabel('Block start 2', { exact: true }).fill('2030-09-21T18:15');
  await program.getByLabel('Block end 2', { exact: true }).fill('2030-09-21T21:00');
  await program.getByRole('button', { name: 'Apply', exact: true }).click();
  await editor.getByLabel('Event opens', { exact: true }).fill('2030-09-22T18:00');
  await expect(program.getByLabel('Block start 1', { exact: true })).toHaveValue('2030-09-22T18:00');
  await expect(editor.getByLabel('Event ends', { exact: true })).toHaveValue('2030-09-22T22:00');
  page.once('dialog', async (dialog) => { expect(dialog.message()).toContain('Tea'); await dialog.dismiss(); });
  await editor.getByLabel('Event ends', { exact: true }).fill('2030-09-22T18:30');
  await expect(editor.getByLabel('Event ends', { exact: true })).toHaveValue('2030-09-22T22:00');
  page.once('dialog', async (dialog) => { expect(dialog.message()).toContain('delete'); await dialog.accept(); });
  await editor.getByLabel('Event ends', { exact: true }).fill('2030-09-22T18:30');
  await expect(program.locator('.program-block')).toHaveCount(1);
  await expect(program.getByLabel('Block end 1', { exact: true })).toHaveValue('2030-09-22T18:30');
  const travel = editor.locator('.travel-time-disclosure');
  await travel.locator(':scope > summary').click();
  await expect(travel.getByLabel('Travel time amount')).toHaveValue('');
  await travel.getByRole('button', { name: '45 min', exact: true }).click();
  await expect(travel.getByLabel('Travel time amount')).toHaveValue('45');
  for (const theme of ['light', 'dark'] as const) {
    await page.emulateMedia({ colorScheme: theme });
    await expect(page.locator('html')).toHaveAttribute('data-theme', theme);
    const addButton = program.getByRole('button', { name: 'Add block', exact: true });
    await expect(addButton).toBeEnabled();
    await expect(addButton).toHaveCSS('background-color', theme === 'dark' ? 'rgb(0, 0, 0)' : 'rgb(255, 255, 255)');
    await expect(addButton).toHaveCSS('color', theme === 'dark' ? 'rgb(241, 241, 241)' : 'rgb(13, 13, 13)');
    await program.scrollIntoViewIfNeeded();
    expect(await editor.evaluate((node) => node.scrollWidth <= node.clientWidth + 1)).toBe(true);
    await page.screenshot({ path: test.info().outputPath(`program-${theme}.png`) });
  }
  await editor.getByRole('button', { name: 'Save item', exact: true }).click();
  await expect(editor).toBeHidden();
  await page.getByText('Program workshop', { exact: true }).first().click();
  await program.locator(':scope > summary').click();
  await expect(program.locator('.program-block')).toHaveCount(1);
  await program.getByRole('button', { name: 'Apply', exact: true }).click();
  await editor.locator('[data-editor-section="more"] > summary').click();
  const scripts = editor.locator('details').filter({ has: page.locator('summary').filter({ hasText: /^Scripts/ }) }).last();
  await scripts.locator(':scope > summary').click();
  await expect(scripts.locator('.item-script-row')).toHaveCount(1);
  await expect(scripts.getByText('Automatically managed · Event program')).toBeVisible();
  await editor.getByRole('button', { name: 'Cancel', exact: true }).click();
  await expect(editor).toBeHidden();
});
