import { test, expect } from '@playwright/test';

for (const colorScheme of ['light', 'dark'] as const) test('quick session survives closing in ' + colorScheme, async ({ page }) => {
  await page.emulateMedia({ colorScheme });
  await page.goto('/');
  await page.getByLabel('Workspace name').fill('Quick sessions');
  await page.getByLabel('Password', { exact: true }).fill('test-password-326');
  await page.getByLabel('Confirm password').fill('test-password-326');
  await page.getByRole('button', { name: 'Create encrypted workspace' }).click();
  const capture = page.locator('[data-quick-capture] input');
  await expect(capture).toBeVisible();
  const nav = page.getByRole('navigation', { name: 'Quick navigation' });
  await expect(nav).toBeVisible();
  const navBox = (await nav.boundingBox())!, inputBox = (await capture.boundingBox())!;
  expect(navBox.x + navBox.width).toBeLessThanOrEqual(inputBox.x);
  expect(Math.abs((navBox.y + navBox.height / 2) - (inputBox.y + inputBox.height / 2))).toBeLessThan(12);
  await page.evaluate(() => document.documentElement.classList.add('keyboard-open'));
  await expect(nav).toBeHidden();
  await page.evaluate(() => document.documentElement.classList.remove('keyboard-open'));
  await capture.focus();
  await page.evaluate(() => { document.documentElement.dataset.nativeKeyboardOpen = 'true'; window.dispatchEvent(new Event('utm:native-keyboard')); });
  await expect(nav).toBeHidden();
  await capture.blur();
  await expect(nav).toBeHidden();
  await page.evaluate(() => { document.documentElement.dataset.nativeKeyboardOpen = 'false'; window.dispatchEvent(new Event('utm:native-keyboard')); });
  await expect(nav).toBeVisible();
  await capture.fill('с'); await capture.press('Enter');
  const dialog = page.getByRole('dialog', { name: 'Timer and stopwatch', exact: true });
  await expect(dialog).toBeVisible();
  await expect(dialog).toHaveClass(/is-glass/);
  expect(await dialog.evaluate(el => getComputedStyle(el).backdropFilter)).not.toBe('none');
  await expect(dialog.getByRole('button', { name: 'Stop', exact: true })).toBeVisible();
  await dialog.getByRole('button', { name: 'Close dialog' }).click();
  await capture.fill('timer'); await capture.press('Enter');
  await expect(dialog.getByRole('button', { name: 'Stop', exact: true })).toBeVisible();
  await dialog.getByRole('button', { name: 'Stop', exact: true }).click();
  await expect(dialog.getByText('Result saved.', { exact: false })).toBeVisible();
  await dialog.getByLabel('Search item').fill('Recorded work');
  await dialog.getByRole('button', { name: 'Create item', exact: true }).click();
  await expect(dialog.getByLabel('Attach to item')).not.toHaveValue('');
  await page.keyboard.press('Escape');
  await expect(dialog).not.toBeVisible();
  await capture.fill('timer'); await capture.press('Enter');
  await expect(dialog.getByLabel('Attach to item').locator('option:checked')).toHaveText('Recorded work');
  await dialog.getByLabel('Search item').fill('RECORDED');
  const results = dialog.getByRole('region', { name: 'Search results' });
  await expect(results.getByRole('button', { name: 'Recorded work', exact: true })).toBeVisible();
  await results.getByRole('button', { name: 'Recorded work', exact: true }).click();
  await expect(dialog.getByLabel('Search item')).toHaveValue('');
  await dialog.getByLabel('Search item').fill('no matching item');
  await expect(results.getByRole('status')).toHaveText('Found: 0');
  await dialog.getByRole('button', { name: 'Close dialog' }).click();
  if ((page.viewportSize()?.width ?? 0) > 620) await page.locator('.sidebar').getByRole('button', { name: 'Settings', exact: true }).click();
  else { await page.getByRole('button', { name: 'Open navigation' }).click(); await page.locator('.mobile-nav-menu').getByRole('button', { name: 'Settings', exact: true }).click(); }
  await page.locator('summary').filter({ hasText: /^Guide$/ }).click();
  await expect(page.locator('.settings-guide details[open]')).toHaveCount(0);
  await page.locator('summary').filter({ hasText: /^Idea & scenarios$/ }).click();
  await page.locator('summary').filter({ hasText: /^Quick entry commands$/ }).click();
  const commands = page.locator('details').filter({ has: page.locator(':scope > summary').filter({ hasText: /^Quick entry commands$/ }) });
  await expect(commands.locator('details[open]')).toHaveCount(0);
  for (const summary of await commands.locator('details > summary').all()) await summary.click();
  const guide = page.locator('.settings-guide');
  await expect(guide).toBeVisible();
  expect(await guide.evaluate(element => element.scrollWidth <= element.clientWidth + 1)).toBe(true);
  for (const code of await guide.locator('code').all()) expect(await code.evaluate(element => element.scrollWidth <= element.clientWidth + 1)).toBe(true);
});
