import type { WorkspaceLanguage } from '@utm/core';

type ReleaseTranslations = Record<Exclude<WorkspaceLanguage, 'en'>, Record<string, string>>;

export const release1963TranslationKeys = [
  'Guide', 'How Universal starts', 'Presets',
  'These values come from the same defaults used to create a new workspace. Existing workspaces keep their own customized values.',
  'Starter Home views', 'Available View templates', 'Calendar day view', 'Workspace settings',
  'Filter', 'Schedule sources', 'Displayed fields', 'Sorting', 'Week starts', 'Monday', 'Sunday', 'Calendar',
  'Working hours', 'Default Duration', 'Appearance', 'Detailed explanations', 'Off', 'Backup reminder', 'Diagnostics', 'On', 'Background push',
  'Area', 'Project', 'Tag', 'Delete Area', 'Delete Project', 'Delete Tag', 'Delete permanently',
  'This operation can change many workspace records.', 'This changes structured workspace data:',
  'linked items will lose this', 'Projects will be detached from this Area, but the Projects will remain.',
  'scoped saved views and their dashboard widgets will be removed.', 'View creation defaults will be cleaned.',
  'free-form View filters or sorts mention this name.', 'They cannot be rewritten safely and may stop matching after deletion. Review them manually.',
  'Make an encrypted backup first if you may need to restore these links.', 'Type', 'to confirm', 'Deletion confirmation',
  'Rules are applied in this order. Unified organization uses the highest matching Area, Project, Tag or No… entry, regardless of relationship type. Time attention keeps overdue and active work ahead of the nearest future boundary.',
  'Every Area, Project and Tag attached to an item competes in this one ladder. Its highest matching row wins; every row remains draggable.',
] as const;

export const release1963Translations: ReleaseTranslations = {
  ru: {
    Guide: 'Руководство', 'How Universal starts': 'Начальные настройки Universal', Presets: 'Предустановки',
    'These values come from the same defaults used to create a new workspace. Existing workspaces keep their own customized values.': 'Эти значения берутся из тех же предустановок, по которым создаётся новое пространство. Существующие пространства сохраняют свои настройки.',
    'Starter Home views': 'Начальные виды Home', 'Available View templates': 'Доступные шаблоны видов', 'Calendar day view': 'Дневной вид календаря', 'Workspace settings': 'Настройки пространства',
    Filter: 'Фильтр', 'Schedule sources': 'Источники расписания', 'Displayed fields': 'Отображаемые поля', Sorting: 'Сортировка', 'Week starts': 'Начало недели', Monday: 'Понедельник', Sunday: 'Воскресенье', Calendar: 'Календарь',
    'Working hours': 'Рабочие часы', 'Default Duration': 'Длительность по умолчанию', Appearance: 'Оформление', 'Detailed explanations': 'Подробные пояснения', Off: 'Выкл.', 'Backup reminder': 'Напоминание о копии', Diagnostics: 'Диагностика', On: 'Вкл.', 'Background push': 'Фоновые уведомления',
    Area: 'Область', Project: 'Проект', Tag: 'Тег', 'Delete Area': 'Удалить область', 'Delete Project': 'Удалить проект', 'Delete Tag': 'Удалить тег', 'Delete permanently': 'Удалить навсегда',
    'This operation can change many workspace records.': 'Эта операция может изменить множество записей пространства.', 'This changes structured workspace data:': 'Будут изменены структурированные данные пространства:',
    'linked items will lose this': 'связанных элементов потеряют эту связь:', 'Projects will be detached from this Area, but the Projects will remain.': 'Проекты будут отвязаны от этой области, но сами проекты сохранятся.',
    'scoped saved views and their dashboard widgets will be removed.': 'связанных сохранённых видов и их виджетов будут удалены.', 'View creation defaults will be cleaned.': 'Предустановки создания во Views будут очищены.',
    'free-form View filters or sorts mention this name.': 'произвольных фильтров или сортировок Views содержат это имя.', 'They cannot be rewritten safely and may stop matching after deletion. Review them manually.': 'Их нельзя безопасно переписать автоматически: после удаления они могут перестать находить элементы. Проверьте их вручную.',
    'Make an encrypted backup first if you may need to restore these links.': 'Сначала создайте зашифрованную копию, если эти связи могут понадобиться для восстановления.',
    Type: 'Введите', 'to confirm': 'для подтверждения', 'Deletion confirmation': 'Подтверждение удаления',
    'Rules are applied in this order. Unified organization uses the highest matching Area, Project, Tag or No… entry, regardless of relationship type. Time attention keeps overdue and active work ahead of the nearest future boundary.': 'Правила применяются по порядку. Общая организация берёт самое высокое совпадение Area, Project, Tag или No… независимо от типа связи. Временная срочность ставит просроченные и активные элементы выше ближайшей будущей границы.',
    'Every Area, Project and Tag attached to an item competes in this one ladder. Its highest matching row wins; every row remains draggable.': 'Все Area, Project и Tag, прикреплённые к item, участвуют в одной лестнице. Побеждает самая высокая совпавшая строка; каждую строку можно перетаскивать.',
  },
  es: {
    Guide: 'Guía', 'How Universal starts': 'Cómo inicia Universal', Presets: 'Preajustes',
    'These values come from the same defaults used to create a new workspace. Existing workspaces keep their own customized values.': 'Estos valores proceden de los mismos ajustes usados al crear un espacio nuevo. Los espacios existentes conservan sus personalizaciones.',
    'Starter Home views': 'Vistas iniciales de Inicio', 'Available View templates': 'Plantillas de vista disponibles', 'Calendar day view': 'Vista diaria del calendario', 'Workspace settings': 'Ajustes del espacio', Filter: 'Filtro', 'Schedule sources': 'Fuentes de programación', 'Displayed fields': 'Campos mostrados', Sorting: 'Ordenación', 'Week starts': 'La semana empieza', Monday: 'Lunes', Sunday: 'Domingo', Calendar: 'Calendario', 'Working hours': 'Horario laboral', 'Default Duration': 'Duración predeterminada', Appearance: 'Apariencia', 'Detailed explanations': 'Explicaciones detalladas', Off: 'Desactivado', 'Backup reminder': 'Recordatorio de copia', Diagnostics: 'Diagnóstico', On: 'Activado', 'Background push': 'Notificaciones en segundo plano',
    Area: 'Área', Project: 'Proyecto', Tag: 'Etiqueta', 'Delete Area': 'Eliminar área', 'Delete Project': 'Eliminar proyecto', 'Delete Tag': 'Eliminar etiqueta', 'Delete permanently': 'Eliminar definitivamente', 'This operation can change many workspace records.': 'Esta operación puede cambiar muchos registros del espacio.', 'This changes structured workspace data:': 'Esto cambia datos estructurados del espacio:', 'linked items will lose this': 'elementos vinculados perderán esta relación:', 'Projects will be detached from this Area, but the Projects will remain.': 'Los proyectos se desvincularán de esta área, pero permanecerán.', 'scoped saved views and their dashboard widgets will be removed.': 'vistas guardadas vinculadas y sus widgets se eliminarán.', 'View creation defaults will be cleaned.': 'Se limpiarán los valores de creación de las vistas.', 'free-form View filters or sorts mention this name.': 'filtros u órdenes libres de vistas mencionan este nombre.', 'They cannot be rewritten safely and may stop matching after deletion. Review them manually.': 'No se pueden reescribir con seguridad y pueden dejar de coincidir. Revísalos manualmente.', 'Make an encrypted backup first if you may need to restore these links.': 'Crea antes una copia cifrada si puedes necesitar restaurar estas relaciones.', Type: 'Escribe', 'to confirm': 'para confirmar', 'Deletion confirmation': 'Confirmación de eliminación',
    'Rules are applied in this order. Unified organization uses the highest matching Area, Project, Tag or No… entry, regardless of relationship type. Time attention keeps overdue and active work ahead of the nearest future boundary.': 'Las reglas se aplican en orden. La organización unificada usa la coincidencia más alta de Área, Proyecto, Etiqueta o No…, sin preferencia por el tipo de relación. La urgencia temporal mantiene primero lo vencido y activo, antes del límite futuro más cercano.',
    'Every Area, Project and Tag attached to an item competes in this one ladder. Its highest matching row wins; every row remains draggable.': 'Cada Área, Proyecto y Etiqueta del elemento compite en una sola escala. Gana la fila coincidente más alta y todas las filas se pueden arrastrar.',
  },
  de: {
    Guide: 'Anleitung', 'How Universal starts': 'So startet Universal', Presets: 'Voreinstellungen',
    'These values come from the same defaults used to create a new workspace. Existing workspaces keep their own customized values.': 'Diese Werte stammen aus denselben Vorgaben wie ein neuer Arbeitsbereich. Bestehende Arbeitsbereiche behalten ihre Anpassungen.',
    'Starter Home views': 'Startansichten', 'Available View templates': 'Verfügbare Ansichtsvorlagen', 'Calendar day view': 'Kalender-Tagesansicht', 'Workspace settings': 'Arbeitsbereich-Einstellungen', Filter: 'Filterbedingung', 'Schedule sources': 'Zeitplanquellen', 'Displayed fields': 'Angezeigte Felder', Sorting: 'Sortierung', 'Week starts': 'Wochenbeginn', Monday: 'Montag', Sunday: 'Sonntag', Calendar: 'Kalender', 'Working hours': 'Arbeitszeit', 'Default Duration': 'Standarddauer', Appearance: 'Darstellung', 'Detailed explanations': 'Ausführliche Erklärungen', Off: 'Aus', 'Backup reminder': 'Backup-Erinnerung', Diagnostics: 'Diagnose', On: 'Ein', 'Background push': 'Hintergrundbenachrichtigungen',
    Area: 'Bereich', Project: 'Projekt', Tag: 'Schlagwort', 'Delete Area': 'Bereich löschen', 'Delete Project': 'Projekt löschen', 'Delete Tag': 'Schlagwort löschen', 'Delete permanently': 'Endgültig löschen', 'This operation can change many workspace records.': 'Dieser Vorgang kann viele Datensätze ändern.', 'This changes structured workspace data:': 'Dabei werden strukturierte Daten geändert:', 'linked items will lose this': 'verknüpfte Elemente verlieren diese Zuordnung:', 'Projects will be detached from this Area, but the Projects will remain.': 'Projekte werden von diesem Bereich getrennt, bleiben aber erhalten.', 'scoped saved views and their dashboard widgets will be removed.': 'zugehörige gespeicherte Ansichten und Widgets werden entfernt.', 'View creation defaults will be cleaned.': 'Erstellungsvorgaben der Ansichten werden bereinigt.', 'free-form View filters or sorts mention this name.': 'freie Ansichtsfilter oder Sortierungen nennen diesen Namen.', 'They cannot be rewritten safely and may stop matching after deletion. Review them manually.': 'Sie können nicht sicher umgeschrieben werden und funktionieren danach möglicherweise nicht mehr. Prüfe sie manuell.', 'Make an encrypted backup first if you may need to restore these links.': 'Erstelle zuerst ein verschlüsseltes Backup, falls du diese Verknüpfungen wiederherstellen musst.', Type: 'Gib', 'to confirm': 'zur Bestätigung ein', 'Deletion confirmation': 'Löschbestätigung',
    'Rules are applied in this order. Unified organization uses the highest matching Area, Project, Tag or No… entry, regardless of relationship type. Time attention keeps overdue and active work ahead of the nearest future boundary.': 'Die Regeln gelten der Reihe nach. Die einheitliche Organisation verwendet den höchsten Treffer aus Bereich, Projekt, Schlagwort oder Kein…, unabhängig vom Beziehungstyp. Zeitliche Dringlichkeit setzt überfällige und aktive Elemente vor die nächste künftige Grenze.',
    'Every Area, Project and Tag attached to an item competes in this one ladder. Its highest matching row wins; every row remains draggable.': 'Jeder Bereich, jedes Projekt und jedes Schlagwort eines Elements konkurriert in derselben Rangliste. Der höchste Treffer gewinnt; jede Zeile bleibt verschiebbar.',
  },
  fr: {
    Guide: 'Mode d’emploi', 'How Universal starts': 'Configuration initiale d’Universal', Presets: 'Préréglages',
    'These values come from the same defaults used to create a new workspace. Existing workspaces keep their own customized values.': 'Ces valeurs viennent des mêmes réglages que ceux d’un nouvel espace. Les espaces existants conservent leurs personnalisations.',
    'Starter Home views': 'Vues d’accueil initiales', 'Available View templates': 'Modèles de vues disponibles', 'Calendar day view': 'Vue journalière du calendrier', 'Workspace settings': 'Réglages de l’espace', Filter: 'Filtre', 'Schedule sources': 'Sources du planning', 'Displayed fields': 'Champs affichés', Sorting: 'Tri', 'Week starts': 'Début de semaine', Monday: 'Lundi', Sunday: 'Dimanche', Calendar: 'Calendrier', 'Working hours': 'Heures de travail', 'Default Duration': 'Durée par défaut', Appearance: 'Apparence', 'Detailed explanations': 'Explications détaillées', Off: 'Désactivé', 'Backup reminder': 'Rappel de sauvegarde', Diagnostics: 'Diagnostic', On: 'Activé', 'Background push': 'Notifications en arrière-plan',
    Area: 'Domaine', Project: 'Projet', Tag: 'Étiquette', 'Delete Area': 'Supprimer le domaine', 'Delete Project': 'Supprimer le projet', 'Delete Tag': 'Supprimer l’étiquette', 'Delete permanently': 'Supprimer définitivement', 'This operation can change many workspace records.': 'Cette opération peut modifier de nombreux enregistrements.', 'This changes structured workspace data:': 'Cela modifie les données structurées suivantes :', 'linked items will lose this': 'éléments liés perdront cette association :', 'Projects will be detached from this Area, but the Projects will remain.': 'Les projets seront détachés de ce domaine, mais resteront disponibles.', 'scoped saved views and their dashboard widgets will be removed.': 'vues enregistrées associées et leurs widgets seront supprimés.', 'View creation defaults will be cleaned.': 'Les valeurs de création des vues seront nettoyées.', 'free-form View filters or sorts mention this name.': 'filtres ou tris libres de vues mentionnent ce nom.', 'They cannot be rewritten safely and may stop matching after deletion. Review them manually.': 'Ils ne peuvent pas être réécrits sans risque et peuvent cesser de fonctionner. Vérifiez-les manuellement.', 'Make an encrypted backup first if you may need to restore these links.': 'Créez d’abord une sauvegarde chiffrée si vous devez pouvoir restaurer ces associations.', Type: 'Saisissez', 'to confirm': 'pour confirmer', 'Deletion confirmation': 'Confirmation de suppression',
    'Rules are applied in this order. Unified organization uses the highest matching Area, Project, Tag or No… entry, regardless of relationship type. Time attention keeps overdue and active work ahead of the nearest future boundary.': 'Les règles s’appliquent dans l’ordre. L’organisation unifiée utilise la correspondance la plus haute parmi Domaine, Projet, Étiquette ou Aucun…, sans préférence de type. L’urgence temporelle place les éléments en retard et actifs avant la prochaine limite future.',
    'Every Area, Project and Tag attached to an item competes in this one ladder. Its highest matching row wins; every row remains draggable.': 'Chaque domaine, projet et étiquette de l’élément participe à la même priorité. La ligne correspondante la plus haute gagne et chaque ligne reste déplaçable.',
  },
  ko: {
    Guide: '가이드', 'How Universal starts': 'Universal 초기 설정', Presets: '사전 설정',
    'These values come from the same defaults used to create a new workspace. Existing workspaces keep their own customized values.': '이 값은 새 작업 공간을 만들 때 사용하는 기본값과 같습니다. 기존 작업 공간은 사용자 설정을 유지합니다.',
    'Starter Home views': '초기 홈 보기', 'Available View templates': '사용 가능한 보기 템플릿', 'Calendar day view': '캘린더 일간 보기', 'Workspace settings': '작업 공간 설정', Filter: '필터', 'Schedule sources': '일정 소스', 'Displayed fields': '표시 필드', Sorting: '정렬', 'Week starts': '주 시작', Monday: '월요일', Sunday: '일요일', Calendar: '캘린더', 'Working hours': '근무 시간', 'Default Duration': '기본 소요 시간', Appearance: '모양', 'Detailed explanations': '자세한 설명', Off: '끔', 'Backup reminder': '백업 알림', Diagnostics: '진단', On: '켬', 'Background push': '백그라운드 알림',
    Area: '영역', Project: '프로젝트', Tag: '태그', 'Delete Area': '영역 삭제', 'Delete Project': '프로젝트 삭제', 'Delete Tag': '태그 삭제', 'Delete permanently': '영구 삭제', 'This operation can change many workspace records.': '이 작업은 많은 작업 공간 레코드를 변경할 수 있습니다.', 'This changes structured workspace data:': '다음 구조화된 데이터가 변경됩니다:', 'linked items will lose this': '개의 연결된 항목에서 이 연결이 제거됩니다:', 'Projects will be detached from this Area, but the Projects will remain.': '프로젝트는 이 영역에서 분리되지만 프로젝트 자체는 유지됩니다.', 'scoped saved views and their dashboard widgets will be removed.': '개의 연결된 저장 보기와 대시보드 위젯이 제거됩니다.', 'View creation defaults will be cleaned.': '보기 생성 기본값이 정리됩니다.', 'free-form View filters or sorts mention this name.': '개의 자유 형식 보기 필터 또는 정렬이 이 이름을 참조합니다.', 'They cannot be rewritten safely and may stop matching after deletion. Review them manually.': '안전하게 자동 수정할 수 없으며 삭제 후 일치하지 않을 수 있습니다. 직접 확인하세요.', 'Make an encrypted backup first if you may need to restore these links.': '이 연결을 복원해야 할 수 있다면 먼저 암호화된 백업을 만드세요.', Type: '입력', 'to confirm': '확인', 'Deletion confirmation': '삭제 확인',
    'Rules are applied in this order. Unified organization uses the highest matching Area, Project, Tag or No… entry, regardless of relationship type. Time attention keeps overdue and active work ahead of the nearest future boundary.': '규칙은 위에서 아래로 적용됩니다. 통합 조직은 관계 유형과 관계없이 영역, 프로젝트, 태그 또는 없음… 중 가장 높은 항목을 사용합니다. 시간 긴급도는 기한이 지난 항목과 활성 항목을 가장 가까운 미래 경계보다 앞에 둡니다.',
    'Every Area, Project and Tag attached to an item competes in this one ladder. Its highest matching row wins; every row remains draggable.': '항목에 연결된 모든 영역, 프로젝트, 태그가 하나의 우선순위에서 경쟁합니다. 가장 높은 일치 행이 적용되며 모든 행을 드래그할 수 있습니다.',
  },
};
