import type { ReactNode } from 'react';
import type { UniversalItem, WorkspaceDocument } from '@utm/core';
import { SectionGuide } from '../../../../components/ui/SectionGuide';
import { formatViewDate } from '../../../../utils/dates';
import { toIsoDuration, type FriendlyDurationUnit } from '../../../../utils/durations';
import { FieldIconLabel } from '../../FieldIcon';

type Props = {
  item: UniversalItem; workspace: WorkspaceDocument; sectionMark: (filled: boolean) => ReactNode;
  recurring: boolean; setRecurring: (value: boolean) => void;
  patchRecurrence: (patch: Partial<NonNullable<UniversalItem['recurrence']>>) => void;
  repeatFrequency: string; repeatInterval: number; repeatIntervalDraft: string; setRepeatIntervalDraft: (value: string) => void;
  repeatUnit: string; repeatDays: string[]; updateRrule: (changes: Record<string, string | undefined>) => void;
  activeRange: boolean; activation: { amount: number; unit: FriendlyDurationUnit };
};

export function RecurrenceSection({ item, workspace, sectionMark, recurring, setRecurring, patchRecurrence, repeatFrequency, repeatInterval, repeatIntervalDraft, setRepeatIntervalDraft, repeatUnit, repeatDays, updateRrule, activeRange, activation }: Props) {
  return <details><summary><FieldIconLabel path="recurrence.rrule" label="Recurrence & auto-renew" /> {sectionMark(recurring)}</summary><div className="details-body">
    <label className="check"><input type="checkbox" checked={recurring} onChange={(event) => { const enabled = event.target.checked; setRecurring(enabled); if (enabled && !item.recurrence) patchRecurrence({ rrule: 'FREQ=WEEKLY;INTERVAL=1' }); }} /> Make this a recurring series</label>
    {recurring && <>
      <SectionGuide title="How recurring items work"><ul><li>A series is one source item; each cycle has its own history.</li><li><strong>Only show during the active range</strong> uses Event opens and Due: complete once during that period, then the next cycle waits until it opens.</li><li>Most weekly tasks only need Repeat and, optionally, the active range. Advanced settings are for unusual activation and auto-close rules.</li></ul></SectionGuide>
      <div className="form-grid two"><label>Repeat<select aria-label="Repeat frequency" value={repeatFrequency} onChange={(event) => { const frequency = event.target.value; updateRrule({ FREQ: frequency, BYDAY: frequency === 'WEEKLY' ? (repeatDays.join(',') || undefined) : undefined }); setRepeatIntervalDraft(String(repeatInterval || 1)); }}><option value="MINUTELY">Minutes</option><option value="HOURLY">Hours</option><option value="DAILY">Daily</option><option value="WEEKLY">Weekly</option><option value="MONTHLY">Monthly</option><option value="YEARLY">Yearly</option></select></label><label>Every<input type="number" min="1" aria-label="Repeat interval" value={repeatIntervalDraft} onChange={(event) => setRepeatIntervalDraft(event.target.value)} onBlur={() => { const value = Math.max(1, Number(repeatIntervalDraft) || 1); setRepeatIntervalDraft(String(value)); updateRrule({ INTERVAL: String(value) }); }} /><span className="field-suffix">{repeatInterval === 1 ? repeatUnit : `${repeatUnit}s`}</span></label></div>
      <p className="field-hint recurrence-anchor-help">The cycle follows the date and time in <strong>Event opens</strong>. If <strong>Due / Active range ends</strong> is set, it defines the end of each cycle's active window.</p>
      <label className="check completion-anchor-toggle"><input type="checkbox" checked={item.recurrence?.anchor === 'completion'} onChange={(event) => patchRecurrence({ anchor: event.target.checked ? 'completion' : 'schedule' })} /><span><strong>Repeat after completion</strong><small>Count the selected interval from the actual completion time: days, weeks, months or years.</small></span></label>
      {!activeRange && repeatFrequency === 'WEEKLY' && <div className="weekday-picker" aria-label="Repeat on weekdays"><span className="field-hint">Choose days for regular repeating tasks or habits.</span>{[['MO', 'M'], ['TU', 'T'], ['WE', 'W'], ['TH', 'T'], ['FR', 'F'], ['SA', 'S'], ['SU', 'S']].map(([value, label]) => <button className={repeatDays.includes(value!) ? 'active' : ''} aria-label={`Repeat on ${value}`} key={value} onClick={() => { const days = repeatDays.includes(value!) ? repeatDays.filter((day) => day !== value) : [...repeatDays, value!]; updateRrule({ BYDAY: days.length ? days.join(',') : undefined }); }}>{label}</button>)}</div>}
      <label className="active-window-toggle"><input type="checkbox" checked={activeRange} onChange={(event) => { if (event.target.checked) updateRrule({ BYDAY: undefined }); patchRecurrence(event.target.checked ? { activationOffset: 'PT0M', closeAt: 'due', autoRenew: true } : { closeAt: 'next_activation' }); }} /><span><strong>Only show during the active range</strong><small>Complete once between Event opens and Due / Active range ends. Outside that range, no active item is shown. The opening date supplies the weekly cycle day.</small></span></label>
      {activeRange && <div className={`active-window-summary ${item.schedule?.startAt && item.schedule?.dueAt ? '' : 'incomplete'}`}><span><small>Event opens</small>{item.schedule?.startAt ? formatViewDate(item.schedule.startAt, true, workspace.calendarPreferences.language) : 'Set Event opens'}</span><span><small>Active range ends</small>{item.schedule?.dueAt ? formatViewDate(item.schedule.dueAt, true, workspace.calendarPreferences.language) : 'Set Due'}</span></div>}
      <details className="advanced-recurrence"><summary>Advanced recurrence behavior</summary><div className="details-body"><div className="form-grid two"><label>Activate before<div className="duration-control"><input type="number" min="0" aria-label="Activation amount" value={activation.amount} onChange={(event) => patchRecurrence({ activationOffset: toIsoDuration(Math.max(0, Number(event.target.value) || 0), activation.unit) })} /><select aria-label="Activation unit" value={activation.unit} onChange={(event) => patchRecurrence({ activationOffset: toIsoDuration(activation.amount, event.target.value as FriendlyDurationUnit) })}><option value="minutes">Minutes</option><option value="hours">Hours</option><option value="days">Days</option><option value="weeks">Weeks</option></select></div></label><label>Auto-close<select value={item.recurrence?.closeAt ?? 'next_activation'} onChange={(event) => patchRecurrence({ closeAt: event.target.value as NonNullable<UniversalItem['recurrence']>['closeAt'] })}><option value="next_activation">At next activation</option><option value="due">At due time</option><option value="never">Never</option></select></label></div><label>Next cycle starts from<select value={item.recurrence?.anchor ?? 'schedule'} onChange={(event) => patchRecurrence({ anchor: event.target.value as NonNullable<UniversalItem['recurrence']>['anchor'] })}><option value="schedule">Scheduled time</option><option value="completion">Actual completion or cancellation</option></select><small>Choose actual completion when the next interval should be counted from the time you finished, rather than the original schedule.</small></label><label className="check"><input type="checkbox" checked={item.recurrence?.autoRenew ?? true} onChange={(event) => patchRecurrence({ autoRenew: event.target.checked })} /> Auto-close untouched cycles</label><label>Repeat rule <span className="hint">RRULE — Recurrence Rule</span><input className="mono" value={item.recurrence?.rrule ?? 'FREQ=WEEKLY;INTERVAL=1'} onChange={(event) => patchRecurrence({ rrule: event.target.value })} /></label><label>Activation duration <span className="hint">ISO 8601</span><input className="mono" value={item.recurrence?.activationOffset ?? 'P7D'} onChange={(event) => patchRecurrence({ activationOffset: event.target.value })} /></label></div></details>
    </>}
  </div></details>;
}
