import type { ReactNode } from 'react';
import { createId, type UniversalItem } from '@utm/core';
import { CloseIcon } from '../../../../components/ui/icons';
import { SectionGuide } from '../../../../components/ui/SectionGuide';
import { FieldIconLabel } from '../../FieldIcon';
import { dateInput, fromDateInput } from '../../../../utils/dates';
import { parseReminderDuration, reminderIsoDuration, type ReminderDurationUnit } from '../../../../utils/durations';

type Props = { item: UniversalItem; now: Date; sectionMark: (filled: boolean) => ReactNode; patchItem: (patch: { [Key in keyof UniversalItem]?: UniversalItem[Key] | undefined }) => void };

export function RemindersSection({ item, now, sectionMark, patchItem }: Props) {
  return <details><summary><FieldIconLabel path="reminders" label="Reminders" /> {sectionMark(item.reminders.length > 0)}</summary><div className="details-body">
    <p className="schedule-explainer">Notifications can happen before or at any important moment, independently of the scheduled time and deadline.</p>
    <SectionGuide title="How reminders behave"><p>Use more than one reminder when needed. Due reminders for the same item are shown as one card with a count. Closing the pop-up only hides it; deleting it from Notifications confirms those reminders so they do not return after the next unlock.</p></SectionGuide>
    {item.reminders.map((reminder, index) => { const relative = reminder.mode === 'relative'; const parsed = parseReminderDuration(reminder.offset); return <div className="reminder-row" key={reminder.id}><select aria-label={`Reminder ${index + 1} mode`} value={relative ? (parsed.before ? 'before' : 'after') : 'absolute'} onChange={(event) => patchItem({ reminders: item.reminders.map((entry, at) => { if (at !== index) return entry; const mode = event.target.value; return mode === 'absolute' ? { ...entry, mode: 'absolute', at: entry.at ?? now.toISOString() } : { ...entry, mode: 'relative', relativeTo: 'start', offset: reminderIsoDuration(parsed.amount, parsed.unit).replace(/^/, mode === 'before' ? '-' : '') }; }) })}><option value="absolute">At time</option><option value="before">Before Event opens</option><option value="after">After Event opens</option></select>{relative ? <><input type="number" min="1" aria-label={`Reminder ${index + 1} amount`} value={parsed.amount} onChange={(event) => patchItem({ reminders: item.reminders.map((entry, at) => at === index ? { ...entry, offset: reminderIsoDuration(Math.max(1, Number(event.target.value) || 1), parsed.unit).replace(/^/, parsed.before ? '-' : '') } : entry) })} /><select aria-label={`Reminder ${index + 1} unit`} value={parsed.unit} onChange={(event) => patchItem({ reminders: item.reminders.map((entry, at) => at === index ? { ...entry, offset: reminderIsoDuration(parsed.amount, event.target.value as ReminderDurationUnit).replace(/^/, parsed.before ? '-' : '') } : entry) })}><option>seconds</option><option>minutes</option><option>hours</option><option>days</option><option>weeks</option><option>months</option><option>years</option></select></> : <input aria-label={`Reminder ${index + 1} time`} type="datetime-local" value={dateInput(reminder.at)} onInput={(event) => patchItem({ reminders: item.reminders.map((entry, at) => { if (at !== index) return entry; const next = { ...entry }; const value = fromDateInput(event.currentTarget.value); if (value) next.at = value; else delete next.at; return next; }) })} />}<select aria-label={`Reminder ${index + 1} urgency`} value={reminder.urgency} onChange={(event) => patchItem({ reminders: item.reminders.map((entry, at) => at === index ? { ...entry, urgency: event.target.value as typeof entry.urgency } : entry) })}><option>normal</option><option>urgent</option><option>critical</option></select><button aria-label="Remove reminder" onClick={() => patchItem({ reminders: item.reminders.filter((_, at) => at !== index) })}><CloseIcon /></button></div>; })}
    <button className="secondary" onClick={() => patchItem({ reminders: [...item.reminders, { id: createId(), mode: 'absolute', at: item.schedule?.startAt ?? now.toISOString(), urgency: 'normal', repeatUntilAcknowledged: false }] })}>+ Add reminder</button>
  </div></details>;
}
